config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/about', to:'static_pages#about'
  get '/signup', to:'users#new'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new,:create,:edit,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :user_name, presence: true, length: { maximum: 50 }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: true
  has_secure_password
  validates :birthday, presence: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("{#attribute}_digest")
    return false if digest.nil?
    BCrypy::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end
  
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end


  def create_reset_digest
	  self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_send_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  def password_reset_expired?
    reset_sent_at 2.hours.ago
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = "Account activated!"
      redirect_to user
    else
      flash[:danger] = "Invalid activation link"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user , only:[:edit, :update]
  before_action :valid_user , only:[:edit, :update]
  before_action :check_expiration , only:[:edit, :update]
  
  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instractions."
      redirect_to root_url
    else
      flash.now[:denger] = "Email address not found"
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, :blank)
      render 'edit'
    elsif @user.update(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "Password has been reseted."
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private
    
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
    
    def get_user
      @user = User.find_by(email: params[:email])
    end
    
    def valid_user
      unless ( @user && @user.activated? && @user.authenticated?(:reset, params[:id]))
      redirect_to root_url
      end
    end
    
    def check_expiration
      if @user.password_reset_expired?
        flash[:denger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user &.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or user
      else
        message = "Account not Acivated."
        message += "Check your Email for activation link."
        flash[:email] = message
        redirect_to root_url
      end  
    else
      flash.now[:denger] = 'Invalid Email/Password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    # @users = User.all
    @users = User.where(activated: true).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url and return unless @user.activated?
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end

    def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_url
    end
  end

  private
    def user_params
      params.require(:user).permit(:user_name, :name, :email, :birthday, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:denger] = "Please login."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end  

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id ||= cookies.signed[:user_id])
      user = User.find_by(id: user.id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user && user == current_user
  end


  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80 )
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar rounded-circle")
  end
end 

app/views/layouts/_header.html.slim
header class="sticky-top"
  nav class="navbar navbar-expand-md navbar-dark bg-dark"
    button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"
      span class="navbar-toggler-icon"
    a class="navbar-brand center" href="#" Sma-R
    div class="collapse navbar-collapse" id="navbarCollapse"
      ul class="navbar-nav mr-auto"
        li class="nav-item"
          a class="nav-link" href="#" ホーム
        li class="nav-item"
          a class="nav-item" href="#" Sma-R
    div class="dropdown"
      button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ◯
      div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton"
        a.dropdown-item
          = link_to "Profile", current_user
        a.dropdown-item
          = link_to "Login", login_path
        a.dropdown-item
          = link_to "Logout", logout_path, method: :delete

app/views/layouts/_rails_default.html.slim
= csrf_meta_tags
= csp_meta_tag
= stylesheet_pack_tag 'application','data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.slim
html
  = render 'layouts/rails_default'
  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        div class=("alert alert-#{message_type}") = message
    = yield
    = debug(params) if Rails.env.development?

app/views/password_resets/edit.html.slim
- provide(:title, 'Reset password')
h1 Reset password
.row
  .col-md-6.col-md-offset-3
    = form_with(model: @user, url: password_resets_path(params[:id]), scope: :password_reset, local: true) do |f|
      
      = render 'shared/error_messages'
      
      = hidden_field_tag :email @user.email
      
      = f.label :password
      = f.password_field :password, class:'form_control'
      
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class:'form_control'
      
      = f.submit "Update Password", class:'btn btn-primary'

app/views/password_resets/new.html.slim
- provide(:title, "Forgot Password")
h1 Forgot Password

.row
  .col-md-6.col-md-offset-3
    = form_with(url: password_resets_path, scope: :password_reset, local: true) do |f|
      = f.label :email
      = f.email_field :email, class:'form_control'

      = f.submit "Submit", class:'btn btn-primary'

app/views/shared/_error_messages.html.slim
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      | The form contains #{pluralize(@user.errors.count, "error")}.
    ul
      - @user.errors.full_messages.each do |msg|
        li= msg

app/views/static_pages/about.html.slim
h1 Sma-R とは
p 口コミサイト・公式サイトのスペック情報だけではわからない、ユーザーの使用状況にあわせた口コミを提供・投稿するサイトです。

app/views/static_pages/home.html.slim
h1 StaticPages#home
p Find me in app/views/static_pages/home.html.slim

app/views/users/_user.html.slim
ul.container
	- @users.each do |user|
		li.container.row.my-3
			= gravatar_for user, size: 50
			p.px-2.text-center
				= link_to user.name, user
			- if current_user.admin? && !current_user?(user)
				|| #{link_to "delete", user, method: :delete, data: { confirm: "You Sure?" }} 

app/views/users/edit.html.slim
- provide(:title, "Edit User")

h1 Update Your Profile
.row
  .col-md-6.col-md-offset-3
    = form_with(model: @user, local: true) do |f|
      = render 'shared/error_messages'

      = f.label :name
      = f.text_field :name, class: 'form-control' 

      = f.label :email
      = f.text_field :email, class: 'form-control' 

      = f.label :password
      = f.text_field :password, class: 'form-control' 

      = f.label :password_confirmation, "Confirmation"
      = f.text_field :password_confirmation, class: 'form-control' 

      = f.submit "Save changes", class: "btn btn-primary"
      = f.text_field :, class ='form-control' 
    - end

    .gravatar_edit
      = gravatar_for @user
      a.href "https://gravatar.com/emails", target="_blank" change

app/views/users/index.html.slim
- provide(:title, 'All users')
h1.container All users

= render 'user'
= page_entries_info @users
= paginate @users

app/views/users/new.html.slim
- provide(:title,'Sign Up')

h1.mx-4 ユーザー登録

.row
  .col-6.col-offset-3
    = form_with(model: @user, local: true) do |f|
      == render 'shared/error_messages'
      / ユーザー名
      = f.label :user_name
      = f.text_field :user_name, class: 'form-control'
      / 氏名
      .col-6
        = f.label :name
        = f.text_field :name, class: 'form-control'
      / E-mail アドレス
      .col-6
        = f.label :email
        = f.text_field :email, class: 'form-control'
      / 生年月日
      .col-6
        = f.label :birthday
        = f.text_field :birthday, class: 'form-control'
        p 例:1990年1月11日
        p 1990-01-11
      / パスワード
      .col-6
        = f.label :password
        = f.text_field :password, class: 'form-control'
      / パスワード再入力
      .col-6
        = f.label :password_confirmation, "Confirm"
        = f.text_field :password_confirmation, class: 'form-control'
      / ボタン
      .col-6
        = f.submit class: "btn btn-primary mx-4 my-4"

app/views/users/show.html.slim
- provide(:title, @user.name)

div.container
  div.row
    div.col-4
      = gravatar_for @user
    div.col-8 
      div.container
        h1
          = @user.name
        p
          = @user.email
div.container
  div.row
    div.col-4
      h3 Posts
      p xxx
    div.col-4
      h3 Like
      p xxx
    div.col-4
      h3 follow
      p xxx

- if current_user.admin?
  .container
    = link_to "Show All User", users_path